image: node:7.9.0

services:
    - docker:dind

variables:
    CONTAINER_IMAGE: 'container-image-url'

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn global add -g mocha istanbul
    - yarn test

deploy:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
    only:
        - master

cache:
  untracked: true
  paths:
    - node_modules/
