image: docker:latest

services:
    - docker:dind

variables:
    CONTAINER_IMAGE: 91556483586.dkr.ecr.eu-west-2.amazonaws.com/wwwonderful/aws-docker

stages:
  - build
  - testing
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn install -g mocha istanbul

testing:
  stage: testing
  script:
    - yarn test

deploy:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli

cache:
  untracked: true
  paths:
    - node_modules/
