image: node:7.9.0

services:
    - docker:dind

variables:
    CONTAINER_IMAGE: 'container-image-url'

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - yarn install
        - yarn global add -g mocha istanbul
        - yarn build
    artifacts:
        paths:
            - node_modules/
            - dist/

test:
    stage: test
    script:
        - yarn test

deploy:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
    only:
        - master

cache:
    untracked: true
    paths:
        - node_modules/
