image: node:7.9.0

services:
    - docker:dind

variables:
    CONTAINER_IMAGE: 'container-image-url'

stages:
  - build
  - testing
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn install -g mocha istanbul

testing:
  stage: testing
  script:
    - yarn test

deploy:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
    only:
        - master

cache:
  untracked: true
  paths:
    - node_modules/
