image: node:7.9.0

variables:
    AWS_REPO_URI: 'repo-uri'

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - yarn install
        - yarn global add -g mocha istanbul
        - yarn build
    artifacts:
        paths:
            - node_modules/
            - dist/

test:
    stage: test
    script:
        - yarn test

deploy:
    stage: deploy
    image: docker:latest
    variables:
        DOCKER_PRIVILEGED: 'true'
        DOCKER_DRIVER: 'overlay'
    services:
        - docker:dind
    script:
        - docker build -t wwwonderful/aws-docker .
        - docker run -d -p 8080:8080 wwwonderful/aws-docker
        - sleep 45 # Race condition
        - curl -I --retry 10 --retry-delay 5 http://localhost:8080/health-check
        - docker tag wwwonderful/aws-docker:latest $AWS_REPO_URI:latest
        - ./tools/deployment/deploy.sh
    only:
        - master

cache:
    untracked: true
    paths:
        - node_modules/
