image: node:7.9.0

variables:
    AWS_REPO_URI: 'repo-uri'
    AWS_ACCESS_KEY_ID: 'access-key-id'
    AWS_SECRET_ACCESS_KEY: 'access-key'

stages:
#    - build
#    - test
    - deploy

#build:
#    stage: build
#    script:
#        - yarn install
#        - yarn global add -g mocha istanbul
#        - yarn build
#    artifacts:
#        paths:
#            - node_modules/
#            - dist/
#
#test:
#    stage: test
#    script:
#        - yarn test

deploy:
    stage: deploy
    image: docker:latest
    variables:
        DOCKER_PRIVILEGED: 'true'
        DOCKER_DRIVER: 'overlay'
    services:
        - docker:dind
    script:
       # - docker build -t wwwonderful/aws-docker .
       # - docker tag wwwonderful/aws-docker:latest $AWS_REPO_URI:latest
        - ./tools/deployment/deploy.sh
    only:
        - master

cache:
    untracked: true
    paths:
        - node_modules/
