image: node:7.9.0

services:
    - docker:dind

variables:
    AWS_REPO_URI: 'repo-uri'

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - yarn install
        - yarn global add -g mocha istanbul
        - yarn build
    artifacts:
        paths:
            - node_modules/
            - dist/

test:
    stage: test
    script:
        - yarn test

deploy:
    stage: deploy
    image: python:latest
    script:
        - pip install awscli
        - docker build -t $AWS_REPO_URI
        - docker run -d -p 8080:8080 --name wwwonderful-web $AWS_REPO_URI
        - curl --retry 10 --retry-delay 5 localhost:8080/health-check | grep "Ok!"
    only:
        - master

cache:
    untracked: true
    paths:
        - node_modules/
